### ISSUE TITLE
Management console

### ISSUE THREAD

**Issue by marvin-j97** [marvin-j97/corinth#137]
- [x] Create `app` folder with a Vue 3 Vite app.
- [x] Serve `index.html`, `js` & `css` files over server.
- [ ] Create button component
- [ ] Create input component
- [x] Queue details page
- [x] -> Link to DLQ if it exists
- [ ] optionally poll for data changes
- [ ] Purge queue button
- [ ] Delete queue button
- [ ] Edit queue (description, deduplication time & requeue time)
- [x] Create queue with DLQ
- [ ] Create queue with description
- [ ] Create queue with custom requeue, deduplication time, max size
- [ ] In queue listing, optionally poll for data changes or refresh button
- [x] Show queue's disk & memory size in listing
- [ ] Server info page (index page)
- [ ] Enqueue message(s)
- [ ] Dequeue message(s)
- [ ] Peek queue head
- [ ] Finishing touches/refactor
